# SPDX-License-Identifier: ISC
---
mail_packages:
  - dovecot--
  - dovecot-pigeonhole--
  - opensmtpd-filter-rspamd
  - py3-cryptography
  - rspamd--hyperscan

#
# Domain
#

mail_aliases_root: root
mail_dkim_selector: domain
mail_domain: domain.tld
