# SPDX-License-Identifier: ISC
#
# Copyright (c) 2024 Johnathan C. Maudlin <jcmdln@gmail.com>
---
- name: Mail
  hosts: "{{ target | default('mail') }}"

  any_errors_fatal: true
  gather_facts: false

  roles:
    - role: jcmdln.openbsd.acme
    - role: jcmdln.openbsd.mail
