# SPDX-License-Identifier: ISC
---
- name: Pkg
  hosts: "{{ target | default('all') }}"

  any_errors_fatal: true
  gather_facts: false

  tasks:
    - name: Update packages
      jcmdln.openbsd.pkg:
        name: "*"
        state: latest
