# SPDX-License-Identifier: ISC
---
- name: Python
  hosts: "{{ target | default('all') }}"

  any_errors_fatal: true
  gather_facts: false

  handlers:
    - name: Install Python
      ansible.builtin.raw: pkg_add python3

  tasks:
    - name: Check if Python 3.x is present
      changed_when: not python_check or python_check.rc > 0
      failed_when: false
      notify: Install Python
      register: python_check
      ansible.builtin.raw: command -v python3
