# SPDX-License-Identifier: ISC
---
- name: Sysupgrade
  hosts: "{{ target | default('all') }}"

  any_errors_fatal: true
  gather_facts: false

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 600

  tasks:
    - name: Upgrade to latest release or snapshot
      notify: Reboot
      jcmdln.openbsd.sysupgrade:
        branch: auto
