# SPDX-License-Identifier: ISC
---
- name: Python
  import_playbook: jcmdln.openbsd.python

- name: Pkg
  import_playbook: jcmdln.openbsd.pkg

- name: Syspatch
  import_playbook: jcmdln.openbsd.syspatch
