# SPDX-License-Identifier: ISC
---
- name: Restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted

- name: Restart redis
  ansible.builtin.service:
    name: redis
    state: restarted

- name: Restart rspamd
  ansible.builtin.service:
    name: rspamd
    state: restarted

- name: Restart smtpd
  ansible.builtin.service:
    name: smtpd
    state: restarted
