# SPDX-License-Identifier: ISC
---
name: lint

on:
  pull_request:
    branches: ["**"]
    paths-ignore: ["**.md"]
  push:
    branches: ["**"]
    paths-ignore: ["**.md"]
  workflow_dispatch:

jobs:
  lint:
    name: ${{ matrix.linter }}-${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        linter: [ansible-lint, mypy, ruff]
        os: [ubuntu-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: tox.ini

      - name: Setup Tox cache
        uses: actions/cache@v4
        id: tox
        with:
          key: tox-${{ matrix.linter }}-${{ matrix.python }}-${{ matrix.os }}-${{ hashFiles('tox.ini') }}
          path: .tox/${{ matrix.linter }}

      - name: Install Tox
        run: pip install tox

      - name: Run ${{ matrix.linter }}
        run: tox -e ${{ matrix.linter }}
